### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sonotaku** [sonotaku/furima_28275#12]
## フリマアプリURL
- https://furima-28275.herokuapp.com/
## Basic認証IDとパスワード
- ID : taku
- パスワード : 0223
## 出品者用（test）
- メールアドレス : takumasonoda0223@icloud.com
- パスワード : takuma0223
## 購入者用（test2）
- メールアドレス : takumasonoda0223@gmail.com
- パスワード : takuma0223
## 購入用カードの番号・期限・セキュリティコード
- カード番号 : 4242424242424242
- 期限 : 3(月)/24(年)
- セキュリティコード : 123

**Comment by mo1015** [comment]
苑田さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
[補足]
商品編集ページで「変更する」ボタンを押すと、エラーページが表示されてしまいます。
商品の編集はできておりますが、可能であれば修正しましょう！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
